### ISSUE TITLE
bug: multiple config files with select_tags results in all tags combined

### ISSUE THREAD

**Issue by raittes** [hbagdi/deck#116]
Deck version: v0.7.0 (69bdff4)

Using multiple config files with different select_tags in each
result in all tags ([Content.Info.SelectorTags](https://github.com/hbagdi/deck/blob/ad47106df43a69db8580af6fa04002ebd025e461/file/types.go#L307)) getting combined during [merge](https://github.com/hbagdi/deck/blob/ad47106df43a69db8580af6fa04002ebd025e461/file/readfile.go#L30).

Example:
```
# file1.yaml
_format_version: "1.1"
_info:
  select_tags:
  - tag1
consumers:
- username: someuser1
```

```
# file2.yaml
_format_version: "1.1"
_info:
  select_tags:
  - tag2
consumers:
- username: someuser2
```

Applying (deck sync -s fileX.yaml) each file individually works  
and then, syncing the dir with both files results in conflict,  
because it filters both tags, don't find the existing users and tries to create again:
```
creating consumer someuser1
creating consumer someuser2
Error: 2 errors occurred:
	while processing event: {Create} failed: 409 Conflict {"message":"UNIQUE violation detected on '{username=\"someuser1\"}'","name":"unique constraint violation","fields":{"username":"someuser1"},"code":5}
	while processing event: {Create} failed: 409 Conflict {"message":"UNIQUE violation detected on '{username=\"someuser2\"}'","name":"unique constraint violation","fields":{"username":"someuser2"},"code":5}
```
And inspecting [selectTags from stateBuilder](https://github.com/hbagdi/deck/blob/ad47106df43a69db8580af6fa04002ebd025e461/file/builder.go#L34-L36) results in: [tag1 tag2]

**Comment by hbagdi** [comment]
This is not a bug and is working as expected.
Multiple files in decK are meant to break down a single configuration into multiple files for maintenance reasons only.

You cannot take two different configurations (if selector tags are different, then it is a different set of configuration) and sync them at the same time.

**Comment by dlouzan** [comment]
@hbagdi Just wanted to point that I encountered the same "issue" in our project while setting up automated deployments and it was highly unintuitive for me. The scenario:

- We'd like to break the configuration file into multiple services, each with its own tag, e.g. `service1` and `service2`, and multiple files for each service, probably one for the service and another for the consumers e.g. `service1/services.yaml` and `service1/consumers.yaml`
- Whenever full CI passes and something is merged to master, deploy to the running kong
- Do this via sync of the whole directory of configuration files, making sure that what is deployed is what it's written in the code
- Have the ability to either deploy everything or just a subset of the config, maybe just all the files relevant to a service

Since the deck strategy is to merge all the tags of the different files in the configuration directory, this does not work. It makes us have to write some script that goes through the different directories and apply them in chunks based on the service name (e.g. `deck sync -s kong-conf/service1/` and `deck sync -s kong-conf/service2/`).

Maybe I'm missing some obvious point, or a better way to manage this?

Great work on the project 👍

**Comment by hbagdi** [comment]
> Maybe I'm missing some obvious point, or a better way to manage this?

This is indeed the right way to do this. Can you open a new issue for this discussion rather than talking on this closed and old issue?

**Comment by dlouzan** [comment]
Thanks for the quick answer! I wasn't sure where to ask, since a search already brought me here.

Created https://github.com/hbagdi/deck/issues/189
