### ISSUE TITLE
Advice: How best to organize upstreams/certificates?

### ISSUE THREAD

**Issue by zraider7** [hbagdi/deck#143]
Hey there! 

Love this tool so far and watched the videos and they were awesome. 

I am part of the devops team and we are basically managing a few kong clusters. I definitely like what you were saying for files to be split up into teams (for example) so that they can completely work on their own without messing up anyone else's stuff. That being said, would it be best to also have them include the upstreams in their file along with the services, routes and potential plugins? We have a few upstreams used by many services, so was just wondering what your take is. Good idea to put those shared upstreams along with the certificates?

**Comment by hbagdi** [comment]
> We have a few upstreams used by many services, so was just wondering what your take is. Good idea to put those shared upstreams along with the certificates?

The answer to these things is largely dependent on your org structure and how various teams distribute responsibilities. 
Since a few upstreams are used by many services, it is best to put them in a shared file rather than club them with Services. This ensures removal of a service doesn't break other services (in case an upstream was removed).

**Comment by zraider7** [comment]
Cool, that works. Thanks for your input!
